import "../../styles/globals.css";
import Header from "../components/Header";
import Navigation from "../components/Navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="sticky top-0 z-50">
          <Header />
          <Navigation />
        </div>
        {children}
      </body>
    </html>
  );
}
